version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    image: php:7.4-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
